const ListItemData = [
  {
    id: 1,
    name: "레몬 제스트",
    subName: "#솝 #레몬껍질이송송",
    price: "14,000",
    img: "https://i.postimg.cc/zf2742n9/card-1.jpg",
    tagButton: "NEW",
    alt: "레몬 제스트",
  },
  {
    id: 2,
    name: "루밥 앤드 커스타",
    subName: "#부드러운두유거품 #상큼한오렌지",
    price: "14,000",
    img: "https://i.postimg.cc/QMKKx6LL/card-2.jpg",
    tagButton: "NEW",
    alt: "루밥 앤드 커스타",
  },
  {
    id: 3,
    name: "13 솝 언럭키 포 더트",
    subName: "#솝 #피부를지켜주는오레가노",
    price: "14,000",
    img: "https://i.postimg.cc/pVsW-4D7K/card-3.jpg",
    tagButton: "VEGAN",
    alt: "13 솝 언럭키 포 더트",
  },
  {
    id: 4,
    name: "로즈 아르간",
    subName: "#진짜장미향기 #기품넘치는샤워",
    price: "22,000",
    img: "https://i.postimg.cc/pLFPm3dB/card-4.jpg",
    tagButton: "VEGAN",
    alt: "로즈 아르간",
  },
  {
    id: 5,
    name: "슬리피",
    subName: "#라벤더솝 #편안한휴식이필요한날",
    price: "13,000",
    img: "https://i.postimg.cc/W4mjnrgF/card-5.jpg",
    tagButton: "VEGAN",
    alt: "슬리피",
  },
  {
    id: 6,
    name: "카마",
    subName: "#오래도록사랑받는 #카마마니아",
    price: "13,000",
    img: "https://i.postimg.cc/j5sTk548/card-6.jpg",
    tagButton: "VEGAN",
    alt: "카마",
  },
  {
    id: 7,
    name: "술타나 오브 솝",
    subName: "#솝 #그랜베리열매가송송",
    price: "9,000",
    img: "https://i.postimg.cc/gJNp9WMG/card-7.jpg",
    tagButton: "VEGAN",
    alt: "술타나 오브 솝",
  },
  {
    id: 8,
    name: "보헤미안",
    subName: "#레몬오일 #상큼한충전완료",
    price: "9,000",
    img: "https://i.postimg.cc/Bbb04VyH/card-8.jpg",
    tagButton: "품절",
    alt: "보헤미안",
  },
  {
    id: 9,
    name: "밀키 바",
    subName: "#포근한향기의편안함 #부드러운 우유",
    price: "9,000",
    img: "https://ws.cconma.com/Upload/Product/400x350/2019/01/5c494690da390.jpeg",
    tagButton: "품절",
    alt: "밀키 바",
  },
];

export default ListItemData;
